matrix:
  include:
    - language: python
      python: 3.7
      before_script:
        - cd backend/tests
      script:
        - python -m unittest discover

    - language: node_js
      node_js: 13
      before_script:
        - cd frontend
        - npm install -g react-scripts
        - npm install
      cache:
        directories:
          - node_modules
      script:
        - npm test

notifications:
  email:
    - preetydragonov@snu.ac.kr