language: node_js
node_js: 13
before_script:
  - cd frontend
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run test:coverage

notifications:
  email:
    - preetydragonov@snu.ac.kr

# language: python
# python: 3.7
# before_script:
#   - cd backend/tests
# script:
#   - python -m unittest discover
