version: '3'

services:
    backend:
      image: chullino93/swpp-backend:1.0
      build: ./backend
      command: sh -c "cd backend && python manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/backend
      ports:
        - "8000:8000"
      depends_on:
        - db
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
